Repository avalonmediasystem/avalon, pull requests merged in 2018-08, with the labels that each got.

#3025 Issue#3006
  app/controllers/master_files_controller.rb
  app/models/master_file.rb
  config/routes.rb
  spec/controllers/master_files_controller_spec.rb
  spec/factories/master_files.rb
  spec/fixtures/waveform.json
  spec/models/master_file_spec.rb
Labels: In Review

#3028 Default to using the test ActiveJob adapter to avoid running background jobs
  spec/controllers/bookmarks_controller_spec.rb
  spec/controllers/collections_controller_spec.rb
  spec/controllers/master_files_controller_spec.rb
  spec/controllers/media_objects_controller_spec.rb
  spec/models/collection_spec.rb
  spec/models/master_file_spec.rb
  spec/rails_helper.rb
Labels: In Review

#2703 update travis to build on 2.5
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: In Review

#3029 Issue#3007: add waveform job to ingest API and tests
  app/controllers/media_objects_controller.rb
  spec/controllers/media_objects_controller_spec.rb
Labels: In Review

#3030 Avoid calling fedora to only check existence
  app/models/ability.rb
Labels: In Review

#3032 Ensure the WaveformJob happens before the ActiveEncodeJob::Create job runs
  app/jobs/active_encode_job.rb
  app/models/master_file.rb
  spec/jobs/active_encode_job_spec.rb
  spec/models/master_file_spec.rb
Labels: In Review

#3031 Add missing require
  app/jobs/bulk_action_jobs.rb
Labels: In Review

#3040 Rails 5 fixes
  app/views/bookmarks/update_access_control.html.erb
  app/views/playlists/show.html.erb
Labels: In Review

#3056 API update should force unpublish if passed publish=false
  app/controllers/media_objects_controller.rb
  lib/avalon/intercom.rb
  spec/controllers/media_objects_controller_spec.rb
  spec/lib/avalon/intercom_spec.rb
Labels: In Review

#3051 Fix working file path
  app/jobs/cleanup_working_file_job.rb
  app/models/avalon/rdf_vocab.rb
  app/models/master_file.rb
  lib/avalon/batch/entry.rb
  spec/integration/working_file_path_spec.rb
  spec/jobs/cleanup_working_files_spec.rb
  spec/models/master_file_spec.rb
Labels: In Review, quality assurance, sprint 158

#3039 Add optional support for Google Analytics
  app/views/layouts/avalon.html.erb
  app/views/layouts/embed.html.erb
  app/views/modules/_google_analytics.html.erb
  config/settings.yml
  spec/controllers/application_controller_spec.rb
  spec/controllers/master_files_controller_spec.rb
  spec/views/google_analytics_spec.rb
Labels: In Review

#3055 Fix BatchRegistries#batch_entries
  app/jobs/ingest_batch_status_email_jobs.rb
  app/models/batch_registries.rb
Labels: In Review

#3057 Backports of latest bugfixes from develop for 6.4.4
  app/controllers/media_objects_controller.rb
  app/jobs/ingest_batch_status_email_jobs.rb
  app/models/batch_registries.rb
  app/views/layouts/avalon.html.erb
  app/views/layouts/embed.html.erb
  app/views/modules/_google_analytics.html.erb
  config/settings.yml
  lib/avalon/intercom.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/master_files_controller_spec.rb
  spec/controllers/media_objects_controller_spec.rb
  spec/lib/avalon/intercom_spec.rb
  spec/views/google_analytics_spec.rb
Labels: In Review

#3060 Working file path forward port
  app/jobs/cleanup_working_file_job.rb
  app/models/avalon/rdf_vocab.rb
  app/models/master_file.rb
  lib/avalon/batch/entry.rb
  spec/integration/working_file_path_spec.rb
  spec/jobs/cleanup_working_files_spec.rb
  spec/models/master_file_spec.rb
Labels: In Review, Sprint 159
